### ISSUE TITLE
table alignment RTL-support

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki#2169]
The RTL-support of alignment in tables needs improvement:

```
^default^left  ^  middle  ^  right^
|default|left  |  middle  |  right|
|xxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxx|
```
LTR:

![table_ltr](https://user-images.githubusercontent.com/183250/32982999-0c0ed80a-cc8e-11e7-8e06-5dbf8c27f0f0.png)

RTL:

![table_rtl](https://user-images.githubusercontent.com/183250/32983000-112f66b0-cc8e-11e7-903b-4974168e7616.png)

/lib/styles/all.css
```css
/* table cell alignment */
.leftalign   { text-align: left;   }
.centeralign { text-align: center; }
.rightalign  { text-align: right;  }

```
/lib/plugins/dw2pdf/conf/style.css
```css
/*____________ tables ____________*/

table {
    border-collapse: collapse;
    empty-cells: show;
    border-spacing: 0;
    border: 1px solid @ini_border;
}

caption {
    caption-side: top;
    text-align: left;
}
[dir=rtl] caption {
    text-align: right;
}

th,
td {
    padding: .3em .5em;
    margin: 0;
    vertical-align: top;
    border: 1px solid @ini_border;
}
th {
    font-weight: bold;
    background-color: @ini_background_alt;
    text-align: left;
}
[dir=rtl] th {
    text-align: right;
}
```

What happens is that the `[dir=rtl] th` overrules the `.leftalign .centeralign .rightalign` classes.

Which solution do you prefer:
```css
th {
    text-align: start;
}
```
Note: experimental according to https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

or adding [dir=rtl] version for the `.leftalign .centeralign .rightalign` classes.
