### ISSUE TITLE
Feature request: add CSS classnames based on namespace, pagename, ans namespace depth

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki#2531]
Hi,
In order to help users code things like «set special CSS style to any start page in any namespace» or «add a special background to pages under the `foo:` namespace», It would be nice if DokuWiki added classnames to its main div `<div id="dokuwiki__content">` based on namespace, pagename, and namespace depth.

For example, page `:foo:bar:start` would have this :
`<div id="dokuwiki__content" class="dwn_foo dwn_foo_bar dwn_bar_ dwl_2 dwp_start dwp_foo_bar_start">`

while page `:start` would have this `<div id="dokuwiki__content" class="dwn_ dwn__ dwl_0 dwp_start">`

users could then easily style their pages in userstyle.css file, for example:
```css
/* Pages in the foo namespace have a red background */
#dokuwiki__content.dwn_foo div.page {
  background_color: red;
}
/* Pages named start have an uppercase h1 title */
#dokuwiki__content.dwp_start div.page h1 {
  text-transform: uppercase;
}
```

I wrote a function that computes the class list based on the pageID available in [this gist](https://gist.github.com/schplurtz/eae3763b73311b4ed8648e20ee462dd0)

Each template author would have to add it in her template...

If you happen to like the idea, I can prepare a PR.
