### ISSUE TITLE
Links to the action pages are no longer highlighted in Greebo

### ISSUE THREAD

**Issue by Michaelsy** [splitbrain/dokuwiki#2768]
No earth-shattering problem, but I wanted to mention it anyway: The links to the action pages "Recent Changes", "Media Manager", and so on are no longer highlighted in Greebo when the appropriate page is opened (resp. is the current page). That was still the case in Frusterick Manners.

**Comment by Klap-in** [comment]
You mean the links just below the search field?
It looks like these are just working at: https://www.dokuwiki.org/donate?do=recent

**Comment by Michaelsy** [comment]
> You mean the links just below the search field?

Yes

> It looks like these are just working at: https://www.dokuwiki.org/donate?do=recent

The Link "Recent Changes" on this page is not highlighted. Compare with: http://test3.informantum.de/doku.php?id=start&do=recent

**Comment by Klap-in** [comment]
Aha, I got it.
The CSS styles are still in code: https://github.com/splitbrain/dokuwiki/blob/cbaf278c50e5baf946b3bd606c369735fe0953be/lib/tpl/dokuwiki/css/design.less#L68-L80 but these elements are changed a bit.

old:
```html
<li>
    <a href="/doku.php?id=start&amp;do=recent" class="action recent" accesskey="r" rel="nofollow" title="Recent Changes [R]">Recent Changes</a>
</li>
```
new:
```html
<li class="action recent">
    <a href="/donate?do=recent" title="Recent Changes [r]" rel="nofollow" accesskey="r">Recent Changes</a>
</li>
```

Suggestion for changes:
```css
.mode_admin .action.admin a, 
.mode_login .action.login a, 
.mode_register .action.register a, 
.mode_profile .action.profile a, 
.mode_recent .action.recent a, 
.mode_index .action.index a, 
.mode_media .action.media a, 
.mode_revisions .action.revs a, 
.mode_backlink .action.backlink a, 
.mode_subscribe .action.subscribe a {
    font-weight: bold;
}

```
I guess it is useful to check if there are more uses of `.action.<mode>`
