### ISSUE TITLE
CSS compilation fails with multiple filters

### ISSUE THREAD

**Issue by trailjeep** [splitbrain/dokuwiki#2860]
I found a way to make code blocks look nice in dark templates, but,
adding:
```css
pre.code span {
    -webkit-filter: invert(100%) contrast(75%);
    filter: invert(100%) contrast(75%);
}
```
results in ths error:
```
A fatal error occured during compilation of the CSS files. If you recently installed a new plugin or template it might be broken and you should try disabling it again. [expected color value: failed at `-webkit-filter: invert(100%) contrast(75%);` in /conf/userall.css at line 3]
```
The CSS works fine in Chrome dev tools and is valid according to: [CSS filter Property](https://www.w3schools.com/CSSref/css3_pr_filter.asp)

> Tip: To use multiple filters, separate each filter with a space (See "More Examples" below).

This does not seem related to #2517 as [Configuration Setting: compress](https://www.dokuwiki.org/config:compress) has no effect.

**Comment by phy25** [comment]
`contrast` is a less function which accepts first argument as color. LESS statements are parsed in `.css` and in `.less` files in DokuWiki. You are seeing an expected behavior.

You may want to use:

```less
pre.code span {
    -webkit-filter:  ~"invert(100%) contrast(75%)";
    filter: ~"invert(100%) contrast(75%)";
}
```

References:
- https://www.dokuwiki.org/devel:less
- https://github.com/splitbrain/dokuwiki/issues/2254#issuecomment-386814503
