### ISSUE TITLE
LESS parser error when defining variabe within ruleset

### ISSUE THREAD

**Issue by rellampec** [splitbrain/dokuwiki#3047]
### Context

Trying to implement [Content Nice Boxes](https://www.dokuwiki.org/plugin:wrap:extensions#content_nice_boxes) (WRAP extension) via `conf/userstyle.less` ([devel:css#user_styles](https://www.dokuwiki.org/devel:css#user_styles))

### Error

```
Fatal Error:
====================
parse error: failed at `@border: #announcements.color-set(@value);` line: 57
```

- possible to recreate in the [demo](https://leafo.net/lessphp/#demo) available at the author's website.

### LESS Code

The code was below successfully compiled using the [Less-To-CSS Playground](http://lesscss.org/less-preview/) at [lesscss.org](http://lesscss.org/):

```less
/* CONTAINER CLASS FOR WRAP ANNOUNCEMENTS & DEFAULT COLOURS*/

#announcements() {
  .color-set(green) {
    background-color: #f6fff0;
    border-color: #DEF2CF;
  }
  .color-set(blue) {
    background-color: #f0f8ff;
    border-color: #D9E5FD;

  }
  .color-set(orange) {
    background-color: #fff9f6;
    border-color:  #FEECBD;
  }
  .color-set(red) {
    background-color: #FFF5F5;
    border-color:  #FED1CD;
  }
  .color-set(yellow) {
    background-color: #fffff0;
    border-color: #F8F8B4;
  }
  .color-set(purple) {
    background-color: #fff0ff;
    border-color: #FCD9F1;
  }
  .color-set(aqua) {
    background-color: #f0fffa;
    border-color: #CEE5EE;
  }
}

@colours: green, blue, orange, red, yellow, purple, aqua;

.dokuwiki div.wrap_announcement  {
  padding: 10px 10px 0px;
  margin-bottom: 1.5em;
  overflow: hidden;
  background-color: #eeeeee;
  border: 2px solid #bbbbbb;

  /* DEFAULT COLOURS & MODS FOR HEADINGS IN ANNOUNCEMENTS. */
  h2, h3, h4, h5, h6 {
    padding: 5px 10px 0px;
    padding: 5px 10px 0px;
    margin: -10px -10px 10px;
    border: 0;
    color: #000000;
    background-color: #bbbbbb;
  }
}


each(@colours, {
  @border: #announcements.color-set(@value);

  /* ANNOUNCEMENT COLORS */
.dokuwiki div.wrap_@{value} {
    border: 2px solid ;
    #announcements.color-set(@value);
 }

 /* COLOUR MODS FOR HEADINGS IN ANNOUNCEMENTS. */
.dokuwiki div.wrap_@{value} {
    h2, h3, h4, h5, h6 {
      background-color: @border[border-color];
    }
 }

});

```

---------------

### The possible reason

Although I am not sure if this is the reason, perhaps, as stated in the dokuwiki documentation the reason could be the restrictions of the library used in dokuwiki ([devel:css](https://www.dokuwiki.org/devel:less#less_language_constructs)):

>We're using [lessphp](https://leafo.net/lessphp/) as a parser so any restrictions of that library apply (eg. you can't use JavaScript expressions). 

- as of [this PR](https://www.freelists.org/post/dokuwiki/New-PR-replace-LESS-compiler-with-lesserphp) moved to use [MarkusSchwarz fork](https://github.com/MarcusSchwarz/lesserphp) ([documentation](https://www.maswaba.de/lesserphpdocs/)) of the original project

### Alternative Less options

Restrictions should not apply. We should be able to use the full extension of the language as of [lesscss.org](http://lesscss.org/). There are currently options to parse `less` on server side...

- As an instance: **[less-middleware](https://www.npmjs.com/package/less-middleware) ([GitHub](https://github.com/emberfeather/less.js-middleware))**, working with `Node.js` and `Express.js`.

Also, in the lesscss.org official documentation there is a section about **[Server-Side and Command Line Usage](http://lesscss.org/usage/#command-line-usage-server-side-and-command-line-usage)**.

- this could work out of the box using `shell_exec` ([php7](https://www.php.net/manual/en/function.shell-exec.php)) by giving the correct source and destination files (i.e. depending on if it's a template, a plug-in or the `conf/userstyle.less` file):
```
lessc [option option=parameter ...] <source> [destination]
```
`Dokuwiki` could detect if the command is available, and use the `lessc` command as a primary less parser if the option is available on the host.

And finally, there is a `php` library to parse less: **[lessphp](https://github.com/wikimedia/less.php)** that is maintained by [Wikimedia](https://www.wikimedia.org/)

## This approach has many advantages:

1. it is backwards compatible, as you can make use of a let's say `dokuwiki` [less plugin](http://lesscss.org/features/#plugin-atrules-feature-writing-your-first-plugin) that is loaded at the beginning to make sure the [color placeholders](https://www.dokuwiki.org/devel:style.ini#guaranteed_color_placeholders) are there (i.e. `@ini_background`)
2. you can allow admins to create a new `config/local.less/` folder to organise their `less` files and even `@import` between them ([as so](http://lesscss.org/features/#import-atrules-feature))
  - this could even be available, by following a specific pattern, for dokuwiki plugins and templates
3. next you can integrate the edition of such files via the [Advancedplugin](https://www.dokuwiki.org/plugin:advanced) (currently you can update the `conf/userstyle.css` fle, which saves you considerable time)
4. with such ease to edit `style` files, more extensions to existing plug-ins could be easily documented and listed on the wiki (for example, extending the `WRAP` plug-in in a more organised manner)
5. the above would open new doors to wiki admins to improve the wiki and make easier for them to engage users by solving usability issues
