### ISSUE TITLE
PHP8/exim4/linux issue with email headers (Dokuwiki 2022-07-31 Igor)

### ISSUE THREAD

**Issue by AnonTester** [splitbrain/dokuwiki#3733]
I've upgraded PHP from 7.4 to 8.1 on a Debian 10 linux system with exim4 4.94.2 running Dokuwiki 2022-07-31 Igor and email notifications were not sent out. It was working perfectly fine before the php upgrade.
The email system complained that "A message that you sent contained no recipient addresses, and therefore no delivery could be attempted." even though bcc was used. 
The email header looked like this:
```
To: 
Subject: [WIKINAME] page added: linux:php8-debian11
Return-Path: [removed](mailto:removed)
 X-Mailer: DokuWiki
 X-Dokuwiki-User: removed
 X-Dokuwiki-Title: Wiki Title
 X-Dokuwiki-Server: removed
 X-Auto-Response-Suppress: OOF
 List-Id: removed
 Date: Fri, 05 Aug 2022 10:53:45 +0100
 Bcc: [removed](mailto:removed)
 List-Unsubscribe:
   [<http://removed/doku.php?id=linux:php8-debian11&do=subscribe>](http://removed/doku.php?id=linux:php8-debian11&do=subscribe)
 Message-Id: [<linuxphp8-debian11rev1659693211@removed>](mailto:linuxphp8-debian11rev1659693211@removed)
 MIME-Version: 1.0
 Content-Type: multipart/alternative;
   boundary="__________de3b83efafa486f9769e8bba4e8fa55eXX"
Message-Id: <E1oJu1Z-007rDY-Mw@removed>
From: www-data <www-data@removed>
From: www-data [<removed>](mailto:removed)
X-rewrote-sender: www-data@removed
Date: Fri, 05 Aug 2022 10:53:45 +0100
```
Note the spaces in front of several headers including the BCC line.

After investigating it turned out that this is related to the change of the mail() function in php8 to always use CRLF ("\r\n") in email headers instead of just the typical LF ("\n") on linux systems.
I found the solution in inc/mail.php by changing the MAILHEADER_EOL definition at the top from "\n" to "\r\n".
This might not be the best place to change this and I do not know how other mail systems or operating systems would react to this, but might be useful to someone and preparing a proper adjustment probably based on PHP version and operating system.

```
if(!defined('MAILHEADER_EOL')) define('MAILHEADER_EOL',"\r\n");
```
