### ISSUE TITLE
Request: Add CSS style to code/file tag

### ISSUE THREAD

**Issue by FreakC** [splitbrain/dokuwiki#673]
A few plugins like the _outliner_ plugin use <code>dl/dd/dt</code> tags for formatting their content. Their CSS may clash with the CSS of <code>code/file</code>.

I found the indentation of the _outliner_ plugin to be such a case. The fix is to explicitly set the padding of the container to zero:

``` css
.dokuwiki dl.code dd, .dokuwiki dl.file dd {
    padding: 0px;
}
```
