### ISSUE TITLE
Compression breaks CSS when valid '//' are used

### ISSUE THREAD

**Issue by theolmue** [splitbrain/dokuwiki#683]
I did some changes in layout by using lib/tpl/vector/user/screen.css in Binky. This worked well. Today I upgraded to Ponder Stibbons. After that the configurations in lib/tpl/vector/user/screen.css are ignored. I checked, that the file is in place and unchanged. Any idea, whats wrong?

My screen.css:

``` css
/* en: Place for user defined CSS rules (screen media) - this file can safely be
   preserved when updating. See README for details.

   de: Ort für benutzerdefinierte CSS-Regeln (screen media) - Diese Datei kann
   beim Durchführen von Updates ohne Risiko beibehalten werden. Konsultieren Sie
   die README für Detailinformationen. */



/* Sidebar breiter machen (15em statt 10em) */
div#content,
#head-base,
div#footer,
div#panel,
#p-logo,
#p-logo a,
#left-navigation {
    margin-left: 15em !important;
}
```
