### ISSUE TITLE
css_onelinecomment_cb will strip div#content a[href ^="https://"], css codes

### ISSUE THREAD

**Issue by fbzhong** [splitbrain/dokuwiki#732]
Hi guys,

I encountered a bug in css processing function "css_onelinecomment_cb", as the following:

version: 2014-05-05 "Ponder Stibbons" 
template: https://www.dokuwiki.org/template:vector

The following css will be stripped incorrect:

Before strip:

``` css
div#content a[href ^="https://"],
.link-https {
        background: url(static/3rd/vector/lock-icon.png) center right no-repeat;
        padding: 0 13px 0 0;
}
```

After stip:

``` css
div#content a[href ^="https
.link-https {
        background: url(static/3rd/vector/lock-icon.png) center right no-repeat;
        padding: 0 13px 0 0;
}
```

When I comment the 

``` php
$css = preg_replace_callback('/^.*\/\/.*$/m','css_onelinecomment_cb',$css);
```

everything works fine.

So there must be some issues in *\* css_onelinecomment_cb*\* function. Please verify and fix it.

thanks.
