### ISSUE TITLE
Make the Save button of configuration page more usable

### ISSUE THREAD

**Issue by mat-m** [splitbrain/dokuwiki#764]
Hello

Configuration page could be quite long, and you don't always modify values at the end.
Moreover, we have a `Back to top` link in almost all templates now.

So could we have a `Save` button on top of the **Configuration** page, just before the fieldset ? Or maybe set it as fixed by default at least so we avoid scrolling or searching the `End` key on a laptop keyboard :) ?

Regards

**Comment by vollstock** [comment]
I have to admit, the Save button way at the end of the doc did annoy a lot the last couple of days.
Me too, I came across many occasions, when I was tinkering with one or two settings that I could not use ENTER on. Then scrolling to find the next textfield to hit ENTER feels like a nasty workaround, not good UI.

I was happy finding @mat-m’s snippet. He has made a good suggestion and I will use a similar snippet in my installation now, too:

**`userstyle.css`**
```css
.dokuwiki #config__manager p {
    display: block;
    position: fixed;
    padding: 1em 3em;
    bottom: 0;
    width: 100%;
    background-color: #f3f3f3;
    z-index: 99;
    left: 0;
}

body.mode_admin .dokuwiki {
    margin-bottom: 5em;
}
```

Still, this is not a well thought UI approach. It's a hack.
