### ISSUE TITLE
Problematic whitespace needs removing 

### ISSUE THREAD

**Issue by Ashtagon** [splitbrain/dokuwiki#924]
The standard list syntax generates the following html code:

``` html
<li class="level1"><div class="li">
List item text here
</div></li>
```

Note that there are carriage returns before and after the actual rendered text.

I'm doing some advanced manipulation of the way lists render using css, and that whitespace is causing a problem.

Digression: The normal rendering for a list is:
- one
- two
- three

I want it to render as:

one; two; three

I am using the wrap plugin to generate custom css code. I use content:after css to insert semi-colons, and set the display of each `<li>` element to inline. The carriage return whitespace before and after the text in the html code gets rendered as a space when display: inline is set, because that whitespace is no long at the beginning or end of a block.

My custom css for use with the wrap plugin is:

``` css
div.dokuwiki div.wrap_compact  ul li { display: inline; }
div.dokuwiki div.wrap_compact  ul div.li { display: inline; }

div.dokuwiki div.wrap_compact  ul li:after { content:";"; }
div.dokuwiki div.wrap_compact  ul li:last-child:after { content: none; } /* no semi-colon after the last list item */
```

Is there a css-based solution to this problem, or can this only be fixed by forcing the dokuwiki engine to stop generating the superfluous carriage returns. If the latter, how would I edit the php code to fix the problem?

ETA: I ran a test in which I saved the generated html page to my desktop, edited out those whitespaces manually, then reloaded it. The resulting page displayed as expected, with the extra space characters removed. This confirms that it is those carriage return characters that are getting rendered as spaces.

First reported at forum: https://forum.dokuwiki.org/post/46068
